Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> print "OHM MAHA GANAPATAYENAMAHA"
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("OHM MAHA GANAPATAYENAMAHA")?
>>> print("OHM MAHA GANAPATAYENAMAHA")
OHM MAHA GANAPATAYENAMAHA
>>> print("OHM NAMO VENKATESHAYANAMAHA")
OHM NAMO VENKATESHAYANAMAHA
>>> print("OHM BAVA NARAYANAMAHA")
OHM BAVA NARAYANAMAHA
>>> print("OHM SUBRAMANYESWARAYANAMAHA")
OHM SUBRAMANYESWARAYANAMAHA
>>> print("OHM SRI SAINADAYANAMAHA")
OHM SRI SAINADAYANAMAHA
>>> print 2+5
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(2+5)?
>>> print (2+5)
7
>>> 